Fix "comparison of Float with nil failed"
tagomoris/fluent-plugin-numeric-monitor pull request #20
Opened 2024-08-14 03:39 UTC by rsym

```
2024-07-01 18:29:11 +0900 [warn]: #0 emit transaction failed: error_class=ArgumentError error="comparison of Float with nil failed" location="/var/lib/td-agent/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-numeric-monitor-1.0.3/lib/fluent/plugin/out_numeric_monitor.rb:195:in `>'" tag="*******************"
```

2024-08-14 09:43 UTC, tagomoris commented
@rsym Could you add the test case for your expected input data?

2024-08-18 05:24 UTC, rsym commented
@tagomoris 

I've committed the test case.
Could you please review it again?

```ruby
Started
Finished in 2.605224 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13 tests, 122 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4.99 tests/s, 46.83 assertions/s
```

---

When testing with the unmodified `out_numeric_monitor.rb`, we get this result.

```ruby
Started
F
======================================================================================================================================================================================================================
Failure: test_emit_with_nil_values(NumericMonitorOutputTest): comparison of Float with nil failed.
/path/to/fluent-plugin-numeric-monitor/test/plugin/test_out_numeric_monitor.rb:435:in `rescue in test_emit_with_nil_values'
/path/to/fluent-plugin-numeric-monitor/test/plugin/test_out_numeric_monitor.rb:408:in `test_emit_with_nil_values'
     405:     assert_equal 6, r['key_prefix_num']
     406:   end
     407: 
  => 408:   def test_emit_with_nil_values
     409:     d = create_driver(CONFIG)
     410:     begin
     411:       d.run(default_tag: 'test.tag1') do
======================================================================================================================================================================================================================
Finished in 2.545104 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13 tests, 116 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
92.3077% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
5.11 tests/s, 45.58 assertions/s
rake aborted!
```

2024-08-19 00:07 UTC, tagomoris commented on test/plugin/test_out_numeric_monitor.rb
> +  rescue => e
Remove this `rescue` clause including `flunk(e)`

2024-08-19 00:08 UTC, tagomoris commented on test/plugin/test_out_numeric_monitor.rb
> +    begin
This `begin` clause doesn't have `rescue` nor `ensure`. Please remove this.

2024-08-19 00:08 UTC, tagomoris commented on test/plugin/test_out_numeric_monitor.rb
> +          d.feed({'field1' => nil})
Does this test need 10 input records?
If just 1 input record is enough to cause the error, use just 1 record.

2024-08-19 00:09 UTC, tagomoris requested changes
The test case has additional/confusing lines.
Could you update the test case?

2024-08-21 00:23 UTC, merged

2024-08-21 00:26 UTC, tagomoris commented
Thank you!
I've merged this change and shipped v1.0.4.